server:
  port: 8080
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
wx:
  appid: wxcb63cd6672e7dfe1
  secret: 4a51d7faa50b96cf6bf25a462e7a2bb5
  url: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
myjwt:
  secret: limouren
  timeout: 86400000
conventional:
  max-buy: 999
  year-codes: A,B,C,D,E,F,G,H,I,J,K,L

